/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ClientWhereUniqueInput } from "../../client/base/ClientWhereUniqueInput";
import { ValidateNested, IsOptional, IsInt, Min, Max } from "class-validator";
import { Type } from "class-transformer";
import { LogisticsUpdateManyWithoutOrdersInput } from "./LogisticsUpdateManyWithoutOrdersInput";
import { PaymentUpdateManyWithoutOrdersInput } from "./PaymentUpdateManyWithoutOrdersInput";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";

@InputType()
class OrderUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ClientWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClientWhereUniqueInput)
  @IsOptional()
  @Field(() => ClientWhereUniqueInput, {
    nullable: true,
  })
  client?: ClientWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => LogisticsUpdateManyWithoutOrdersInput,
  })
  @ValidateNested()
  @Type(() => LogisticsUpdateManyWithoutOrdersInput)
  @IsOptional()
  @Field(() => LogisticsUpdateManyWithoutOrdersInput, {
    nullable: true,
  })
  logisticsItems?: LogisticsUpdateManyWithoutOrdersInput;

  @ApiProperty({
    required: false,
    type: () => PaymentUpdateManyWithoutOrdersInput,
  })
  @ValidateNested()
  @Type(() => PaymentUpdateManyWithoutOrdersInput)
  @IsOptional()
  @Field(() => PaymentUpdateManyWithoutOrdersInput, {
    nullable: true,
  })
  payments?: PaymentUpdateManyWithoutOrdersInput;

  @ApiProperty({
    required: false,
    type: () => ProductWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProductWhereUniqueInput)
  @IsOptional()
  @Field(() => ProductWhereUniqueInput, {
    nullable: true,
  })
  product?: ProductWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  quantity?: number | null;
}

export { OrderUpdateInput as OrderUpdateInput };
